name: dada_app
description: "تطبيق إدارة صالة DADA GYM الرياضية"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  mobile_scanner: ^7.0.1
  flutter_facebook_auth: ^7.1.2
  flutter_secure_storage: ^9.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"