// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4IM8o1HvGGBMAysqiXE3JRPAyccWtIqU',
    appId: '1:845064281911:web:32e61edc65c4cc973004b2',
    messagingSenderId: '845064281911',
    projectId: 'gymdada-b1ef0',
    authDomain: 'gymdada-b1ef0.firebaseapp.com',
    storageBucket: 'gymdada-b1ef0.firebasestorage.app',
    measurementId: 'G-CT2PDQ7QL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcH_KUYCT_p4wjAIkcoLxAPjmtBWRLlAE',
    appId: '1:845064281911:android:e23ed5f1fdf7863b3004b2',
    messagingSenderId: '845064281911',
    projectId: 'gymdada-b1ef0',
    storageBucket: 'gymdada-b1ef0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh2eNN66soTxvZcgiC1s-R7Ii6ivtieJA',
    appId: '1:845064281911:ios:759a0b45924defc73004b2',
    messagingSenderId: '845064281911',
    projectId: 'gymdada-b1ef0',
    storageBucket: 'gymdada-b1ef0.firebasestorage.app',
    iosBundleId: 'com.example.dadaGymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh2eNN66soTxvZcgiC1s-R7Ii6ivtieJA',
    appId: '1:845064281911:ios:759a0b45924defc73004b2',
    messagingSenderId: '845064281911',
    projectId: 'gymdada-b1ef0',
    storageBucket: 'gymdada-b1ef0.firebasestorage.app',
    iosBundleId: 'com.example.dadaGymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4IM8o1HvGGBMAysqiXE3JRPAyccWtIqU',
    appId: '1:845064281911:web:135e9e8254ee87b33004b2',
    messagingSenderId: '845064281911',
    projectId: 'gymdada-b1ef0',
    authDomain: 'gymdada-b1ef0.firebaseapp.com',
    storageBucket: 'gymdada-b1ef0.firebasestorage.app',
    measurementId: 'G-WN6NFDBNJ7',
  );
}
